name: CI

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pipenv"
      - name: Install pipenv
        run: pip install --user pipenv
      - name: Sync
        run: pipenv sync --dev
      - name: Build
        run: python setup.py sdist
      - name: Lint
        run: pipenv run check
      - name: Test
        run: pipenv run test
